apiVersion: v1
kind: Service
metadata:
  name: minizinc-app-service
spec:
  selector:
    app: minizinc-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minizinc-app
spec:
  selector:
    matchLabels:
      app: minizinc-app
  template:
    metadata:
      labels:
        app: minizinc-app
    spec:
      volumes:
        - name:  service-account-key
          secret:
            secretName: storage-key
      containers:
      - name: minizinc-app
        image: minizinc
        ports:
        - containerPort: 80
        volumeMounts:
          - name:  service-account-key
            mountPath: /src/key.json