apiVersion: v1
kind: Service
metadata:
  name: minizinc-app-service
spec:
  selector:
    app: minizinc-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minizinc-app
spec:
  selector:
    matchLabels:
      app: minizinc-app
  template:
    metadata:
      labels:
        app: minizinc-app
    spec:
      containers:
      - name: minizinc-app
        image: europe-west1-docker.pkg.dev/spherical-being-330016/docker-images/minizinc:latest
        ports:
        - containerPort: 80
      serviceAccountName: sa-storage-account

# The service account must have the following roles:
# roles/iam.workloadIdentityUser
# roles/storage.admin
# How to apply roles see:
# https://cloud.google.com/iam/docs/creating-managing-service-accounts#iam-service-accounts-list-gcloud 